#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done


	if [ ! -f /tmp/state/10-backuppc ]; then
        cp -R /etc/msmtp /home/backuppc/.msmtprc
		mkdir -p /tmp/state/
		echo 'Initialization Complete' >/tmp/state/10-backuppc
               	    
	fi

echo ''
echo '** [backuppc] Starting BackupPC'
exec s6-setuidgid backuppc /usr/local/BackupPC/bin/BackupPC
