#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service defaults single

PROCESS_NAME="backuppc"

check_container_initialized
check_service_initialized 11-fcgiwrap
liftoff

print_start "Starting BackupPC ${BACKUPPC_VERSION}"
silent exec s6-setuidgid backuppc /usr/local/BackupPC/bin/BackupPC
