#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/10-nginx ]
do
  sleep 1
done

source /assets/functions/*
PROCESS_NAME="fcgiwrap"
liftoff

print_info "Starting fcgiwrap"
silent exec /usr/bin/spawn-fcgi  -s /var/run/fcgiwrap.sock -P /var/run/fcgiwrap.pid -u backuppc -g backuppc -U backuppc -G backuppc -M 660 -n -- /usr/bin/fcgiwrap
