#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-lighttpd ]; then

        mkdir -p /tmp/state
	echo 'Initialization Complete' >/tmp/state/10-lighttpd
fi

echo ''
echo '** Starting Lighttpd'
exec /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf -D
