#!/usr/bin/with-contenv bash

  ### Adjust NGINX Runtime Variables
  UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE:-"2G"}
  PORT_NUMBER=${PORT_NUMBER:-"80"}

  sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/nginx/nginx.conf
  sed -i -e "s/<PORT_NUMBER>/$PORT_NUMBER/g" /etc/nginx/conf.d/default.conf
  
  mkdir -p /www/logs/nginx
  chown -R backuppc /www/logs/nginx

  mkdir -p /tmp/state
  touch /tmp/state/09-nginx
