#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="backuppc"

bootstrap_filesystem
create_zabbix backuppc
generate_ssh_keys
install_backuppc
configure_ui

print_info "BackupPC ${BACKUPPC_VERSION} initialization complete, now starting web server on port ${NGINX_LISTEN_PORT}"
liftoff
