#!/usr/bin/with-contenv bash

### Sanity Check Defaults
  AUTHENTICATION_TYPE=${AUTHENTICATION_TYPE:-BASIC}
  BACKUPPC_ADMIN_USER=${BACKUPPC_ADMIN_USER:-backuppc}
  BACKUPPC_ADMIN_PASS=${BACKUPPC_ADMIN_PASS:-backuppc}

  chown -R backuppc:backuppc /var/tmp/nginx

### Map Authentication

  case "$AUTHENTICATION_TYPE" in
      "BASIC")
      sed -ie "s/^\$Conf{CgiAdminUsers}\s*=\s*'\w*'/\$Conf{CgiAdminUsers} = '$BACKUPPC_ADMIN_USER'/g" /etc/backuppc/config.pl
      htpasswd -b -c /etc/backuppc/htpasswd $BACKUPPC_ADMIN_USER $BACKUPPC_ADMIN_PASS
  	  sed -i "/error_log/a\ \ \  include /etc/nginx/conf.d/authtypes/basic.auth;" /etc/nginx/conf.d/default.conf
  	  echo '** [backuppc] Setting Basic Authentication'
      ;;
      "LLNG")
      sed -ie "s/^\$Conf{CgiAdminUsers}\s*=\s*'\w*'/\$Conf{CgiAdminUsers} = '$BACKUPPC_ADMIN_USER'/g" /etc/backuppc/config.pl
  	  sed -i "/error_log/a\ \ \  include /etc/nginx/conf.d/authtypes/llng.auth;" /etc/nginx/conf.d/default.conf
  	  sed -i "s/<LLNG_HANDLER_HOST>/$LLNG_HANDLER_HOST/g" /etc/nginx/conf.d/authtypes/llng.auth
  	  sed -i "s/<LLNG_HANDLER_PORT>/$LLNG_HANDLER_PORT/g" /etc/nginx/conf.d/authtypes/llng.auth
  	  echo '** [backuppc] Setting LLNG Authentication'
      ;;
      "NONE")
	  sed -i "/error_log/a\ \ \  include /etc/nginx/conf.d/authtypes/none.auth;" /etc/nginx/conf.d/default.conf      
	  echo '** [backuppc] No Authentication Settings. A bad idea if this is used for production purposes!'
      ;;
     *)
      sed -ie "s/^\$Conf{CgiAdminUsers}\s*=\s*'\w*'/\$Conf{CgiAdminUsers} = '$BACKUPPC_ADMIN_USER'/g" /etc/backuppc/config.pl
	  htpasswd -b -c /etc/backuppc/htpasswd $BACKUPPC_ADMIN_USER $BACKUPPC_ADMIN_PASS
	  sed -i "/error_log/a\ \ \  include /etc/nginx/conf.d/authtypes/basic.auth;" /etc/nginx/conf.d/default.conf
	  echo '** [backuppc] Setting Basic Authentication'
	  ;;
  esac
