#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/20-nginx ]
do
  sleep 1
done

if [ ! -f /tmp/state/30-fcgwiwrap ]; then
    mkdir -p /tmp/state/
	echo 'Initialization Complete' >/tmp/state/30-fcgiwrap
fi

echo ''
echo '** [fcgiwrap] Starting fcgiwrap'
exec /usr/bin/spawn-fcgi  -s /var/run/fcgiwrap.sock -P /var/run/fcgiwrap.pid -u backuppc -g backuppc -U backuppc -G backuppc -M 660 -n -- /usr/bin/fcgiwrap

