#!/usr/bin/with-contenv bash

	if [ ! -f /tmp/state/30-backuppc ]; then

		mkdir -p /tmp/state/
		echo 'Initialization Complete' >/tmp/state/30-backuppc
	    
	fi

echo ''
echo '** Starting BackupPC..'
exec s6-setuidgid backuppc /usr/local/BackupPC/bin/BackupPC


