#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="backuppc"

check_container_initialized
check_service_initialized init 11-fcgiwrap
cp -R /etc/msmtp /home/backuppc/.msmtprc
liftoff

print_info "Starting BackupPC ${BACKUPPC_VERSION}"
silent exec s6-setuidgid backuppc /usr/local/BackupPC/bin/BackupPC
