#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/11-fcgiwrap ]
do
  sleep 1
done

source /assets/functions/*
PROCESS_NAME="backuppc"
cp -R /etc/msmtp /home/backuppc/.msmtprc
liftoff

print_info "Starting BackupPC ${BACKUPPC_VERSION}"
silent exec s6-setuidgid backuppc /usr/local/BackupPC/bin/BackupPC
