#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/11-fcgiwrap ]
do
  sleep 1
done

### Set Debug Mode
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
    set -x
fi

if [ ! -f /tmp/state/09-backuppc ]; then
    cp -R /etc/msmtp /home/backuppc/.msmtprc
	echo 'Initialization Complete' >/tmp/state/09-backuppc
           	    
fi

echo "** [backuppc] Starting BackupPC ${BACKUPPC_VERSION}"
exec s6-setuidgid backuppc /usr/local/BackupPC/bin/BackupPC
